### ISSUE TITLE
Issue while converting notebook file into html file

### ISSUE THREAD

**Issue by RituLalwani** [SamLau95/nbinteract#148]
I was trying to convert jupyter notebook file to html.
But I am getting below error :
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\nbinteract.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\nbinteract\cli.py", line 173, in main
    run_converter(arguments)
  File "c:\programdata\anaconda3\lib\site-packages\nbinteract\cli.py", line 194, in run_converter
    exporter = init_exporter(
  File "c:\programdata\anaconda3\lib\site-packages\nbinteract\cli.py", line 413, in init_exporter
    exporter = InteractExporter(config=config)
  File "c:\programdata\anaconda3\lib\site-packages\nbinteract\exporters.py", line 125, in __init__
    self.template_path.insert(
AttributeError: 'InteractExporter' object has no attribute 'template_path'

**Comment by clod11235** [comment]
Same here!

**Comment by bnavigator** [comment]
https://github.com/jupyter/nbconvert/pull/1310 template_path does not exist sinc nbconvert 6.0
