### ISSUE TITLE
Binder spec path "is neither an existing file or folder"

### ISSUE THREAD

**Issue by emilydolson** [SamLau95/nbinteract#76]
This looks like a great project! Thanks for developing it!

I'm having some trouble getting my widget/notebook to convert correctly. I've tried doing it both through the CLI and through the nbi.publish() function, and in both cases I get this error:

```
Traceback (most recent call last):
  File "/home/emily/anaconda3/bin/nbinteract", line 11, in <module>
    sys.exit(main())
  File "/home/emily/anaconda3/lib/python3.6/site-packages/nbinteract/cli.py", line 166, in main
    run_converter(arguments)
  File "/home/emily/anaconda3/lib/python3.6/site-packages/nbinteract/cli.py", line 184, in run_converter
    recursive=arguments['--recursive']
  File "/home/emily/anaconda3/lib/python3.6/site-packages/nbinteract/cli.py", line 103, in flatmap
    mapped for item in iterable for mapped in fn(item, *args, **kwargs)
  File "/home/emily/anaconda3/lib/python3.6/site-packages/nbinteract/cli.py", line 103, in <listcomp>
    mapped for item in iterable for mapped in fn(item, *args, **kwargs)
  File "/home/emily/anaconda3/lib/python3.6/site-packages/nbinteract/cli.py", line 367, in expand_folder
    .format(notebook_or_folder)
ValueError: emilydolson/ecology_of_evolutionary_computation/master is neither an existing file nor a folder.
```

This the notebook I'm trying to publish: https://github.com/emilydolson/ecology_of_evolutionary_computation/blob/master/EEBB_talk.ipynb

In case it matters, I'm doing this on Linux Mint 18.3 and Python3 installed through Anaconda. Let me know if there's any more information that would be helpful.

**Comment by SamLau95** [comment]
Hi @emilydolson ! Looks like you're trying to input a URL for conversion. You should instead input a local filepath.

For example, if I `cd` into the same directory as the `EEBB_talk.ipynb` file, I should be able to run something like:

```
nbinteract emilydolson/ecology_of_evolutionary_computation/master EEBB_talk.ipynb
```

**Comment by SamLau95** [comment]
Oops, made a typo; it should be:

```
nbinteract -s emilydolson/ecology_of_evolutionary_computation/master EEBB_talk.ipynb
```
